# Generated by Django 4.1 on 2022-09-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='organisation_id',
            new_name='organization_id',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='organisation_id',
            new_name='organization_id',
        ),
    ]
