# Generated by Django 4.1 on 2022-09-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_rename_organisation_id_employees_organization_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='te_id',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='organisation_address',
            new_name='organization_address',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='organisation_location',
            new_name='organization_location',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='organisation_name',
            new_name='organization_name',
        ),
    ]
